/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Vistas.VistaPrincipal;

/**
 *
 * @author LENOVO
 */
public class Entrada extends javax.swing.JFrame {

    
    public Entrada() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jLabelQueUnd = new javax.swing.JLabel();
        jComboBoxUnidades = new javax.swing.JComboBox<>();
        jButtonEntrar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 51));
        jLabelTitulo.setText("Bienvenido al conversor");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jLabelTitulo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo2.setForeground(new java.awt.Color(255, 255, 0));
        jLabelTitulo2.setText("De unidades");
        getContentPane().add(jLabelTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jLabelQueUnd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelQueUnd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQueUnd.setText("Qué unidades quiere convertir?");
        getContentPane().add(jLabelQueUnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jComboBoxUnidades.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jComboBoxUnidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Divisas", "Distancia", " " }));
        getContentPane().add(jComboBoxUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 140, 20));

        jButtonEntrar.setBackground(new java.awt.Color(153, 204, 255));
        jButtonEntrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonEntrar.setForeground(new java.awt.Color(0, 153, 255));
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(51, 51, 255));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(204, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 60, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cambiar.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        String captura = jComboBoxUnidades.getSelectedItem().toString();
        VistaPrincipal abrir = new VistaPrincipal();
        VistaDistancias abrir2 = new VistaDistancias();        
        if(captura=="Divisas"){            
            abrir.setVisible(true);
            this.setVisible(true);
            abrir2.setVisible(false);
        }else if(captura=="Distancia"){
            abrir.setVisible(false);
            abrir2.setVisible(true);
            this.setVisible(true);
        }
        
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxUnidades;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelQueUnd;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo2;
    // End of variables declaration//GEN-END:variables
}
